import com.mysql.cj.jdbc.exceptions.CommunicationsException;

import java.awt.*;
import java.sql.*;
import javax.naming.CommunicationException;
import javax.swing.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static final String Username="root";
    public static final String Password="";
    public static int ono=0;
    public static String cid=null;

    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 600));
        setMinimumSize(new java.awt.Dimension(1050, 600));
        setPreferredSize(new java.awt.Dimension(1050, 600));

        jPanel1.setBackground(new java.awt.Color(64, 68, 67));
        jPanel1.setMaximumSize(new java.awt.Dimension(1050, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1050, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 600));
        jPanel1.setLayout(null);
        setResizable(false);
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New to The Ziti Dish?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 240, 200, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SIGN UP!");
        jLabel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(218, 290, 70, 17);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMaximumSize(new java.awt.Dimension(5, 600));
        jSeparator2.setMinimumSize(new java.awt.Dimension(5, 600));
        jSeparator2.setPreferredSize(new java.awt.Dimension(5, 600));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(525, 0, 5, 600);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("THE ZITI DISH");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LOGIN");
        jLabel6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap(70, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                                        .addComponent(jPasswordField1))
                                                .addGap(84, 84, 84))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(113, 113, 113))))
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel6)
                                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(590, 80, 390, 450);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
        // SIGN UP!!!!
        dispose();
        SignUp signup=new SignUp();
        signup.setVisible(true);

    }

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {
        // LOGIN!!!!!!!!!!!!!!
        String username =jTextField1.getText() ;
        String password= jPasswordField1.getText();
        try
        {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/zitipizza?zeroDateTimeBehavior=CONVERT_TO_NULL",Username,Password);
            String sql="select * from Login where username='"+jTextField1.getText()+"' and password='"+jPasswordField1.getText()+"'";
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {

                JOptionPane.showMessageDialog(null,"Login Successfull!!");

                if(rs.getInt("idflag")==1)
                {
                    System.out.println("Entering customer portal");
                    dispose();
                    try
                    {
                        sql="Select c_id from customer where username ='"+jTextField1.getText()+"';";
                        ps=conn.prepareStatement(sql);
                        rs=ps.executeQuery();
                        rs.next();
                        cid=rs.getString("c_id");
                    }
                    catch (Exception e)
                    {
                        System.out.println(e);
                    }
                    Menu menu=new Menu(ono,cid);
                    ono++;
                    menu.setVisible(true);
                }
                else if(rs.getInt("idflag")==2)
                {
                    System.out.println("Entering admin portal");
                    dispose();
                    AdminPage adminPage=new AdminPage();
                    adminPage.setVisible(true);

                }
                else if(rs.getInt("idflag")==3)
                {
                    System.out.println("Entering manager portal");
                    dispose();
                    ManagerAssignOrder managerAssignOrder=new ManagerAssignOrder();
                    managerAssignOrder.setVisible(true);

                }
                else if(rs.getInt("idflag")==4)
                {
                    dispose();

                    try
                    {
                        sql="Select Emp_id from Employee where username ='"+jTextField1.getText()+"';";
                        ps=conn.prepareStatement(sql);
                        rs=ps.executeQuery();
                        rs.next();
                        cid=rs.getString("Emp_id");
                    }
                    catch (Exception e)
                    {
                        System.out.println(e);
                    }
                    ChefPage chefPage=new ChefPage(Integer.parseInt(cid));
                    chefPage.setVisible(true);
                }
                else if(rs.getInt("idflag")==5)
                {
                    dispose();

                    try
                    {
                        sql="Select Emp_id from Employee where username ='"+jTextField1.getText()+"';";
                        ps=conn.prepareStatement(sql);
                        rs=ps.executeQuery();
                        rs.next();
                        cid=rs.getString("Emp_id");
                    }
                    catch (Exception e)
                    {
                        System.out.println(e);
                    }
                    DeliveryPerson deliveryPerson=new DeliveryPerson(Integer.parseInt(cid));
                    deliveryPerson.setVisible(true);
                }

            }



            else
            {
                JOptionPane.showMessageDialog(null,"Credentials not valid\nPlease try again");
            }
        }
        catch(CommunicationsException e)
        {
            JOptionPane.showMessageDialog(null,"Not connected to database. \nPlease check your connection");
            System.out.println(e);
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Could not login\nPlease try again");
            System.out.println(e);
        }
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // USERNAME
    }

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Password
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
}
