import com.mysql.cj.jdbc.exceptions.CommunicationsException;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.naming.CommunicationException;
import javax.swing.*;
import java.util.*;
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    String imgname1 = null;
    String imgname2= null;
    String item1=null;
    String item2=null;
    int pri1=0,pri2 = 0;
    String sl1=null;
    String sl2=null;
    String sql=null;
    String itid1=null;
    String itid2=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    Statement statement=null;
    Connection conn;
    public static int ono;
    public static String cid;
    public Menu(int ono, String cid)
    {
        this.ono=ono;
        this.cid=cid;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/zitipizza?zeroDateTimeBehavior=CONVERT_TO_NULL", Login.Username, Login.Password);
            //statement =conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            sql="select count(*) from cust_order where c_id="+cid+";";
            System.out.println("43"+sql);
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
            if(rs.next())
            {
                if(rs.getInt("count(*)")>0)
                {
                    sql="select order_no from cust_order where c_id="+cid+";";
                    System.out.println("51");
                    System.out.println(sql);
                    ps=conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    rs=ps.executeQuery();
                    rs.next();
                    ono=rs.getInt("Order_no");
                }
                else
                {
                    sql="Insert into cust_order values ("+ono+" , "+cid+");";
                    System.out.println("60"+sql);
                    ps=conn.prepareStatement(sql);
                    ps.executeUpdate();
                }
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            System.out.println("error in 67");
        }
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel7 = new JLabel();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLayeredPane1 = new JLayeredPane();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        Q1 = new JTextField();
        upPrice1 = new JLabel();
        jLabel16 = new JLabel();
        Splvl1 = new JLabel();
        jButton1 = new JButton();
        jLayeredPane2 = new JLayeredPane();
        jLabel5 = new JLabel();
        jLabel18 = new JLabel();
        jLabel19 = new JLabel();
        jLabel20 = new JLabel();
        Q2 = new JTextField();
        upPrice2 = new JLabel();
        jLabel22 = new JLabel();
        splvl2 = new JLabel();
        jButton2 = new JButton();
        jLabel6 = new JLabel();
        jLabel8 = new JLabel();
        setResizable(false);
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/zitipizza?zeroDateTimeBehavior=CONVERT_TO_NULL", Login.Username, Login.Password);
            //statement =conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            sql="select * from menu";
            ps=conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs=ps.executeQuery();
            if(rs.next())
            {

                imgname1=rs.getString("Item_id");
                item1=rs.getString("Item_name");
                pri1=rs.getInt("Price");
                sl1=rs.getString("Spice_Level");
                itid1=rs.getString("Item_id");
                rs.next();
                imgname2=rs.getString("Item_id");
                item2=rs.getString("Item_name");
                pri2=rs.getInt("Price");
                sl2=rs.getString("Spice_Level");
                itid2=rs.getString("Item_id");

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(1050, 600));

        jPanel1.setBackground(new Color(64, 68, 67));
        jPanel1.setMaximumSize(new Dimension(1050, 600));
        jPanel1.setMinimumSize(new Dimension(1050, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new Dimension(1050, 600));
        jPanel1.setLayout(null);

        jLabel7.setFont(new Font("Arial", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel7.setText("The Ziti Dish");

        jLabel11.setFont(new Font("Arial", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel11.setText("CheckOut");
        jLabel11.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new Font("Arial", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel12.setText("View Order");
        jLabel12.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setFont(new Font("Arial", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel13.setText("Logout");
        jLabel13.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13, GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addContainerGap(365, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 190, 600);

        jLayeredPane1.setBackground(new Color(204, 204, 204));
        jLayeredPane1.setForeground(new Color(204, 204, 204));
        jLayeredPane1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLayeredPane1.setMaximumSize(new Dimension(375, 460));
        jLayeredPane1.setMinimumSize(new Dimension(375, 460));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setPreferredSize(new Dimension(375, 460));


        jLabel1.setIcon(new ImageIcon(getClass().getResource(imgname1+".jpg"))); // NOI18N

        jLabel2.setFont(new Font("Times New Roman", 3, 19)); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText(item1);

        jLabel3.setFont(new Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Price:");

        jLabel4.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Quantity:");

        Q1.setFont(new Font("Arial", 0, 14)); // NOI18N

        upPrice1.setFont(new Font("Arial", 0, 14)); // NOI18N
        upPrice1.setForeground(new Color(0, 0, 0));
        upPrice1.setText(Integer.toString(pri1));

        jLabel16.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Spice Level:");

        Splvl1.setFont(new Font("Arial", 0, 14)); // NOI18N
        Splvl1.setText(sl1);

        jButton1.setFont(new Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Q1, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(upPrice1, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel16, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Splvl1, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, JLayeredPane.DEFAULT_LAYER);

        GroupLayout jLayeredPane1Layout = new GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 357, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel1))
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Q1, GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                                        .addComponent(upPrice1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(27, 27, 27)
                                                .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Splvl1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                                        .addComponent(upPrice1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                                .addComponent(Q1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton1))
                                                        .addComponent(jLabel4)))
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Splvl1, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        jLabel6.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel8.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel13.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel12.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel11.setCursor(new Cursor(Cursor.HAND_CURSOR));





        jPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(240, 40, 360, 460);

        jLayeredPane2.setBackground(new Color(204, 204, 204));
        jLayeredPane2.setForeground(new Color(204, 204, 204));
        jLayeredPane2.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLayeredPane2.setMaximumSize(new Dimension(375, 460));
        jLayeredPane2.setMinimumSize(new Dimension(375, 460));
        jLayeredPane2.setOpaque(true);

        jLabel5.setIcon(new ImageIcon(getClass().getResource(imgname2+".jpg"))); // NOI18N

        jLabel18.setFont(new Font("Times New Roman", 3, 19)); // NOI18N
        jLabel18.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel18.setText(item2);

        jLabel19.setFont(new Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Price:");

        jLabel20.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Quantity:");

        Q2.setFont(new Font("Arial", 0, 14)); // NOI18N
        Q1.setText("0");
        Q2.setText("0");

        upPrice2.setFont(new Font("Arial", 0, 14)); // NOI18N
        upPrice2.setForeground(new Color(0, 0, 0));
        upPrice2.setText(Integer.toString(pri2));

        jLabel22.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Spice Level:");

        splvl2.setFont(new Font("Arial", 0, 14)); // NOI18N
        splvl2.setText(sl2);

        jButton2.setFont(new Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel5, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel18, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel19, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel20, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Q2, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(upPrice2, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel22, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(splvl2, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton2, JLayeredPane.DEFAULT_LAYER);

        GroupLayout jLayeredPane2Layout = new GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
                jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 357, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel5))
                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel20)
                                                        .addComponent(jLabel19))
                                                .addGap(18, 18, 18)
                                                .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Q2, GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                                        .addComponent(upPrice2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(27, 27, 27)
                                                .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                                .addComponent(jLabel22)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(splvl2, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
                jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                                .addComponent(jLabel19, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED))
                                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                                .addComponent(upPrice2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(9, 9, 9)))
                                                .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                                .addComponent(Q2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton2))
                                                        .addComponent(jLabel20)))
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel22, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(splvl2, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        jPanel1.add(jLayeredPane2);
        jLayeredPane2.setBounds(645, 40, 360, 460);

        jLabel6.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new Color(255, 255, 255));
        jLabel6.setText("BACK");
        jLabel6.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 550, 40, 17);

        jLabel8.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new Color(255, 255, 255));
        jLabel8.setText("NEXT");

        jLabel8.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(965, 550, 40, 17);

        getContentPane().add(jPanel1, BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // ADD for first item
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/zitipizza?zeroDateTimeBehavior=CONVERT_TO_NULL",Login.Username,Login.Password);
            String sql1="Select price from menu where item_id='"+itid1+"';";
            PreparedStatement ps1=conn.prepareStatement(sql1);
            ResultSet rs1=ps1.executeQuery();
            rs1.next();
            String sql2="Insert into Order_items values ("+ono+",'"+itid1+"',"+Q1.getText() +","+(rs1.getInt("price")*Integer.parseInt(Q1.getText()))+",1);";
            System.out.println(sql2);
            PreparedStatement ps2=conn.prepareStatement(sql2);
            ps2.executeUpdate();
            JOptionPane.showMessageDialog(null,"Item added to cart");
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // ADD for second item
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/zitipizza?zeroDateTimeBehavior=CONVERT_TO_NULL",Login.Username,Login.Password);
            String sql1="Select price from menu where item_id='"+itid2+"';";
            PreparedStatement ps1=conn.prepareStatement(sql1);
            ResultSet rs1=ps1.executeQuery();
            rs1.next();
            String sql2="Insert into Order_items values ("+ono+",'"+itid2+"',"+Q2.getText() +","+(rs1.getInt("price")*Integer.parseInt(Q2.getText()))+",1);";
            System.out.println(sql2);
            PreparedStatement ps2=conn.prepareStatement(sql2);
            ps2.executeUpdate();
            JOptionPane.showMessageDialog(null,"Item added to cart");
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {
        // BACK!!!!!!
        try
        {
            Q1.setText("0");
            Q2.setText("0");

            System.out.println(rs.getString("Item_id"));
            if(rs.previous())
            {
                rs.previous();
                imgname2=rs.getString("Item_id");
                item2=rs.getString("Item_name");
                pri2=rs.getInt("Price");
                sl2=rs.getString("Spice_Level");
                splvl2.setText(sl2);
                itid2=rs.getString("Item_id");
                rs.previous();
                System.out.println(rs.getString("Item_name"));

                System.out.println(1+rs.getString("Item_id"));
                imgname1=rs.getString("Item_id");
                item1=rs.getString("Item_name");
                pri1=rs.getInt("Price");
                sl1=rs.getString("Spice_Level");
                jLabel2.setText(item1);
                jLabel18.setText(item2);
                upPrice1.setText(Integer.toString(pri1));
                upPrice2.setText(Integer.toString(pri1));
                Splvl1.setText(sl1);
                itid1=rs.getString("Item_id");

                jLabel1.setIcon(new ImageIcon(getClass().getResource(imgname1+".jpg")));
                jLabel5.setIcon(new ImageIcon(getClass().getResource(imgname2+".jpg")));
                System.out.println(rs.getString("Item_name"));
                rs.next();


            }
            else
            {
                System.out.println("in else");
                rs=ps.executeQuery();
            }
        }

        catch(Exception e)
        {
            try
            {
                rs.first();
                rs.next();
                System.out.println("in try");
                System.out.println("rs try"+rs.getString("Item_name"));

            }
            catch (Exception en)
            {
                System.out.println(en);
            }
            System.out.println(e);
        }
    }

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {
        // NEXT!@#$%^
        System.out.println("next");
        try
        {
            Q1.setText("0");
            Q2.setText("0");


            System.out.println(rs.getString("Item_id"));
            if(rs.next())
            {

                System.out.println(1+rs.getString("Item_id"));
                imgname1=rs.getString("Item_id");
                item1=rs.getString("Item_name");
                pri1=rs.getInt("Price");
                sl1=rs.getString("Spice_Level");
                itid1=rs.getString("Item_id");
                rs.next();
                imgname2=rs.getString("Item_id");
                item2=rs.getString("Item_name");
                pri2=rs.getInt("Price");
                sl2=rs.getString("Spice_Level");
                jLabel2.setText(item1);
                jLabel18.setText(item2);
                upPrice1.setText(Integer.toString(pri1));
                upPrice2.setText(Integer.toString(pri1));
                Splvl1.setText(sl1);
                splvl2.setText(sl2);
                itid2=rs.getString("Item_id");
                jLabel1.setIcon(new ImageIcon(getClass().getResource(imgname1+".jpg")));
                jLabel5.setIcon(new ImageIcon(getClass().getResource(imgname2+".jpg")));



            }
            else
            {
                try
                {
                    rs.last();

                }
                catch (Exception en)
                {
                    System.out.println(en);
                }
            }
        }
        catch(Exception e)
        {
            try
            {
                rs.last();
                System.out.println("next try "+rs.getString("Item_id"));
            }
            catch (Exception en)
            {
                System.out.println(en);
            }
            System.out.println(e);
        }
    }

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {
        // LOGOUT
        try
        {
            sql="delete from cust_order where order_no="+ono+" and c_id="+cid+";";
            ps=conn.prepareStatement(sql);
            ps.executeUpdate();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        dispose();
        Login login=new Login();
        login.setVisible(true);
    }

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {
        // view order
        dispose();
        ViewOrderScreen viewOrderScreen=new ViewOrderScreen(ono,cid);
        viewOrderScreen.setVisible(true);
    }

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {
        // check out
        dispose();
        OrderScreen orderScreen=new OrderScreen(ono,cid);
        orderScreen.setVisible(true);

    }



    // Variables declaration - do not modify
    private javax.swing.JTextField Q1;
    private javax.swing.JTextField Q2;
    private javax.swing.JLabel Splvl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel splvl2;
    private javax.swing.JLabel upPrice1;
    private javax.swing.JLabel upPrice2;
    // End of variables declaration
}